### ISSUE TITLE
Retrying downloads aggressively

### ISSUE THREAD

**Issue by ctaymor** [concourse/s3-resource#42]
We're seeing failures to put to an S3 resource like this a lot.

```
error running command: read tcp 10.254.1.222:37446->54.231.237.6:443: read: connection reset by peer
```

I see that there was a previous, closed issue https://github.com/concourse/s3-resource/issues/15 with this problem, however, it doesn't seem to have addressed it sufficiently for us. Is it possible to look into increasing the number of retries or other solutions to this problem again?
Thanks.

**Comment by jfrank-pivotal** [comment]
+1 for this issue.  We're seeing this very frequently on our new Concourse 1.3 deployment.  We initially suspected slow downloads or extremely large files, but this is happening even when download speeds and times are reasonable, e.g.:
`505.78 MB / 511.99 MB [================================] 98.79 % 1.16 MB/s 7m16s`.

Interestingly, this is happening almost exclusively in the high 90% range of download completion and in the time range of 7-8 minutes, regardless of whether the size is 500 MB or 1000 MB.  The time and size numbers are probably unrelated, but the fact that it's regularly failing right near the end of the download suggests that perhaps the library or the S3 endpoint are letting the connection close before the final bits are received.

**Comment by ctaymor** [comment]
I'm not sure whether it's relevant, but a quick glance at the most recent failures indicates that this is often the case for us well. I'm seeing failures in the last 2-3% of the upload, speeds > 3MB/s, failing 5-8 minutes into the upload. I'm not seeing any exceptions to this, but I've only checked the last 10 failures or so.

**Comment by zachgersh** [comment]
We've experienced this as well (as have other users in the aws-sdk-go community). I have a suspicion that this is the bug:

https://github.com/aws/aws-sdk-go/issues/466

Of course tis only a guess.

**Comment by vito** [comment]
Should be fixed by @zachgersh's PR.

**Comment by zachgersh** [comment]
@vito - uploads are sadly not fixed. I am actually working toward modifying the s3 library code itself to allow for resuming a download. 

Who knows if that will work out. We're using our own retry logic in a custom s3 resource right now - it works alright except for the fact that we aren't reseting the download progress bar.

**Comment by cholick** [comment]
Is there a new issue for this? I'm looking through the list and not seeing one. Both this issue and #15 have been marked as closed, but the problem persists.
